### ISSUE TITLE
Running Vanilla Phone Simulator Throwing Uncaught TypeError (hasQueueWaitTimeCheckbox)

### ISSUE THREAD

**Issue by estrudels** [salesforce/demo-scv-connector#16]
Hey Demo SCV Connector Team,

I am running the latest **Demo SCV Connector** and I am encountering an issue when it is running.

`Uncaught TypeError: Cannot read properties of null (reading 'addEventListener')
    at ./src/remote-control/main.js (main.js:328:26)
    at __webpack_require__ (bootstrap:19:1)
    at 1 (remote.bundle.js:12285:18)
    at __webpack_require__ (bootstrap:19:1)
    at bootstrap:83:1
    at bootstrap:83:1` 
    
Digging deeper the problem is in the **main.js** files specifically at 
   
`hasQueueWaitTimeCheckbox.addEventListener('change', setCapabilities);`

See screenshot for more information

![Add-Event-Listener-Broken-For-Has-Queue-Wait-Time-Checkbox](https://user-images.githubusercontent.com/100722689/224342306-b58543c0-e05d-4ed4-b17d-7f9587dfca59.png)

These are my exact steps to reproduce

1. Ensure that my machine is running **Node 16** as **SCV Connector Demo** does not work with **Node 18**
2. Ensure that I have a SF SCV Org configured correctly, with a Contact Center which has the Adapter URL pointing to localhost (https://localhost:8080)
4. Clone the Repo for `salesforce/demo-scv-connector`
5. Open the Repo in Visual Studio Code
6. Run the command `npm install` (Confirm All Installed Correctly)
7. Run the command `npm test` (Confirm All Tests Are Passing)
8. Run the command `npm run start` (Confirm That Is Successfully Running)
9. Open Google Chrome and Navigate to `https://localhost:8080/remote` (Confirm That Phone Simulator Loads)
10. I open **Developer Tools for Google Chrome** and notice the `Uncaught Type Error`
11. Furthmore I am able to Login to my SCV SF Org and navigate to the App with SCV App, the **Phone Simulator** then updates to have the appropriate Agent Settings which means my client is talking to the server correctly
12. However then I am unable to make for instance a **Inbound Call** action from the **Phone Simulator**

Could you please confirm that my setup is correct? A couple of fellow coworkers are experiencing the exact same problem.

Also if I try to do some actions I get

`main.js:423 Uncaught TypeError: Cannot read properties of null (reading 'checked')
    at HTMLInputElement.setCapabilities (main.js:423:56)`
    
To confirm my **Client** is taking to **Server** okay I see the following

[0] i ｢wdm｣: Compiled successfully.
[1] TenantInfo configured :
[1] scrtBaseUrl : https://uplandingenius-b-dev-ed.my.salesforce-scrt.com
[1] orgId : 00DB0000000ccwF
[1] callCenterName : IGContactCenter
[1]
[1] User joined: estodola-agent@force.com

Please this app is crucial to be in a **functional** and **running** state so that our developers may properly integrate with SCV Connector, and reference this **Demo SCV Connector** to confirm what vanilla functionality is currently offered, so we understand if we integrate/programmed correctly

Thanks

**Comment by estrudels** [comment]
**FYI** @rjanamanchi-sfdc @vivektikoo-force @dlouvton @v-goyal-sfdc @rxu-sfdc

**Comment by estrudels** [comment]
This issue has been **verified** and is currently being **fixed** by the Salesforce - SCV Connector Demo team

Internal Salesforce Reference Number - W-12672146

**Comment by estrudels** [comment]
Thank you for the quick response acknowledging this issue, and the quick turnaround to get a fix into the master branch. Much thank from the Upland InGenius team!
